# Generated by Django 4.2.1 on 2023-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aflohap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment',
            field=models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], default='P', max_length=1),
        ),
    ]
